name: note_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.1+2

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #data
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  encrypted_shared_preferences: ^3.0.1


  #ui
  google_fonts: ^3.0.1
  flutter_slidable: ^2.0.0

  #utils
  connectivity_plus: ^3.0.2
  double_back_to_close: ^2.0.0
  image_picker: ^0.8.6
  fluttertoast: ^8.1.1
  email_validator: ^2.1.17
  intl: ^0.17.0
  flutter_image_compress: ^1.1.3


  #services
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  firebase_analytics: ^10.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0 
  #flutter pub run change_app_package_name:main com.alissorucu.notes
  build_runner: ^2.3.2

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
